apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mongo-user.yaml
  - mongo-betdata.yaml
  - password.yaml
patches:
  - target:
      namespace: dsbd
      name: mongo-user
    path: user.yaml
  - target:
      namespace: dsbd
      name: mongo-betdata
    path: user.yaml
