version: '3.9'

services:

  mongo:
    image: mongo
    volumes:
      - database:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL

  server:
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_URL
      - DB_PORT
      - DB_DATABASE
    depends_on:
      - mongo
    build:
      context: ./DSBD_Server

  bot:
    environment:
      - BOT_TOKEN_DSBD
    depends_on:
      - server
    build:
      context: ./DSBD_Bot
    volumes:
      - tmpfiles:/tmpfiles

  stats_settings:
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_URL
      - DB_PORT
      - DB_DATABASE
    depends_on:
      - mongo
    build:
      context: ./DSBD_Stats_Settings
    volumes:
      - tmpfiles:/tmpfiles

volumes:
  database:
  tmpfiles: