version: '3.9'

services:

  mongo_betData:
    image: mongo
    volumes:
      - database:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE

  mongo-express-betData:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL

  mongo_parser:
      image: mongo
      volumes:
        - database:/data/db
        - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
        - MONGO_INITDB_DATABASE

  mongo-express_parser:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL

  server:
    image: lauralex/dsbd_server
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_URL
      - DB_PORT
      - DB_DATABASE
    depends_on:
      - mongo
    build:
      context: ./DSBD_Server

  bot:
    image: lauralex/dsbd_bot
    environment:
      - BOT_TOKEN_DSBD
    depends_on:
      - server
    build:
      context: ./DSBD_Bot
    volumes:
      - tmpfiles:/tmpfiles

  stats_settings:
    image: lauralex/dsbd_stats_settings
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_URL
      - DB_PORT
      - DB_DATABASE
    depends_on:
      - mongo
    build:
      context: ./DSBD_Stats_Settings
    volumes:
      - tmpfiles:/tmpfiles

  bet_data_service:
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_URL
      - DB_PORT
      - DB_DATABASE
    build:
      context: ./DSBD_BetDataService
    depends_on:
      - kafka

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - ./kafkavol:/bitnami/kafka

volumes:
  database:
  tmpfiles: