apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
  namespace: dsbd
spec:
  replicas: 2
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: lauralex/dsbd_user_service
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: connectionString.standardSrv
                  name: mongo-user-admin-claudi47
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: database
                  name: dsbd-config
            - name: BROKER
              valueFrom:
                configMapKeyRef:
                  key: broker
                  name: dsbd-config
            - name: SCHEMA_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: schemaRegistry
                  name: dsbd-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: dsbd
spec:
  selector:
    app: user-service
  ports:
    - port: 80
      name: web
      targetPort: 8500
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
  namespace: dsbd
  labels:
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: user-service
  endpoints:
    - port: web
