apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: confluent
  namespace: confluent
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
provisioner: docker.io/hostpath